import type { VisualKey } from '@/content/types'
import { ScreenApprovalMock, ScreenConsentMock, ScreenIntegrityMock, ScreenReportMock, ScreenRoomMock } from './screen'
import { HireMatchMock } from './hirematch'
import { ApplyFormMock, CandidateProfileMock, KanbanMock } from './index'
import { ARMock, InboxMock, JDRubricMock, LevPanelMock, NurtureMock, SourcingMock, SubmitSheetMock, TeamMock } from './hirepilot'

// Maps content-file visual keys to recreated product UI.
const VISUALS: Record<VisualKey, () => JSX.Element> = {
  screenRoom: ScreenRoomMock,
  screenReport: ScreenReportMock,
  screenIntegrity: ScreenIntegrityMock,
  screenConsent: ScreenConsentMock,
  screenApproval: ScreenApprovalMock,
  hpBrief: JDRubricMock,
  hpProfile: CandidateProfileMock,
  hpPipeline: KanbanMock,
  hpLev: LevPanelMock,
  hpInbox: InboxMock,
  hpSubmit: SubmitSheetMock,
  hpAR: ARMock,
  hpNurture: NurtureMock,
  hpTeam: TeamMock,
  hpCareers: ApplyFormMock,
  hpSourcing: SourcingMock,
  hpMatch: HireMatchMock,
}

// Older inline-styled mocks have no Frame; label them here for assistive tech.
const LEGACY_LABELS: Partial<Record<VisualKey, string>> = {
  hpBrief: 'HirePilot job brief generated by AI next to a weighted screening rubric.',
  hpProfile: 'HirePilot candidate profile with a résumé score, matched and missing skills, and activity.',
  hpPipeline: 'HirePilot pipeline board with candidates moving through stages.',
  hpLev: 'Lev, the HirePilot assistant, proposing an action that waits for approval.',
  hpInbox: 'HirePilot unified inbox with email and WhatsApp messages.',
  hpSubmit: 'HirePilot send-to-client view with selected candidates in a summary sheet.',
  hpAR: 'HirePilot receivables list with overdue invoices and an automatic nudge.',
  hpNurture: 'HirePilot nurture timeline of post-placement check-ins.',
  hpTeam: 'HirePilot team view showing workload per recruiter.',
  hpCareers: 'A branded career page application form.',
  hpSourcing: 'HirePilot sourcing view with an AI search string and job posting status.',
}

export function Visual({ name }: { name: VisualKey }) {
  const C = VISUALS[name]
  const label = LEGACY_LABELS[name]
  if (!label) return <C />
  return <div role="img" aria-label={label}><div aria-hidden><C /></div></div>
}
